name: deploy_website
on:
  push:
    branches: main
jobs:
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: Check folder
        run: ls -la
