name: deploy_website
on:
  push:
    branches: main
jobs:
  my_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses: actions/checkout@main
        with:
          repository: 01Yura/Ansible-playbooks

      - name: Deploy
        run: ansible-playbook ansible-user=root ansible-password=02081985YuraPrimyshev playbook_install_apache_and_website.yml
